/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteRouteImport } from './routes/_site/route'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as SiteIndexRouteImport } from './routes/_site/index'
import { Route as ProtectedPaymentScheduleRouteImport } from './routes/_protected/payment-schedule'
import { Route as ProtectedPaymentHistoryRouteImport } from './routes/_protected/payment-history'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as ProtectedDebtsIndexRouteImport } from './routes/_protected/debts/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedDebtsNewRouteImport } from './routes/_protected/debts/new'

const SiteRouteRoute = SiteRouteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRouteRoute,
} as any)
const ProtectedPaymentScheduleRoute =
  ProtectedPaymentScheduleRouteImport.update({
    id: '/payment-schedule',
    path: '/payment-schedule',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedPaymentHistoryRoute = ProtectedPaymentHistoryRouteImport.update({
  id: '/payment-history',
  path: '/payment-history',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDebtsIndexRoute = ProtectedDebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDebtsNewRoute = ProtectedDebtsNewRouteImport.update({
  id: '/debts/new',
  path: '/debts/new',
  getParentRoute: () => ProtectedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/payment-history': typeof ProtectedPaymentHistoryRoute
  '/payment-schedule': typeof ProtectedPaymentScheduleRoute
  '/debts/new': typeof ProtectedDebtsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/debts/': typeof ProtectedDebtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/payment-history': typeof ProtectedPaymentHistoryRoute
  '/payment-schedule': typeof ProtectedPaymentScheduleRoute
  '/debts/new': typeof ProtectedDebtsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/debts': typeof ProtectedDebtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_site': typeof SiteRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/payment-history': typeof ProtectedPaymentHistoryRoute
  '/_protected/payment-schedule': typeof ProtectedPaymentScheduleRoute
  '/_site/': typeof SiteIndexRoute
  '/_protected/debts/new': typeof ProtectedDebtsNewRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_protected/debts/': typeof ProtectedDebtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/payment-history'
    | '/payment-schedule'
    | '/debts/new'
    | '/api/auth/$'
    | '/debts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/dashboard'
    | '/payment-history'
    | '/payment-schedule'
    | '/debts/new'
    | '/api/auth/$'
    | '/debts'
  id:
    | '__root__'
    | '/_protected'
    | '/_site'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/_protected/dashboard'
    | '/_protected/payment-history'
    | '/_protected/payment-schedule'
    | '/_site/'
    | '/_protected/debts/new'
    | '/api/auth/$'
    | '/_protected/debts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  SiteRouteRoute: typeof SiteRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRouteRoute
    }
    '/_protected/payment-schedule': {
      id: '/_protected/payment-schedule'
      path: '/payment-schedule'
      fullPath: '/payment-schedule'
      preLoaderRoute: typeof ProtectedPaymentScheduleRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/payment-history': {
      id: '/_protected/payment-history'
      path: '/payment-history'
      fullPath: '/payment-history'
      preLoaderRoute: typeof ProtectedPaymentHistoryRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/debts/': {
      id: '/_protected/debts/'
      path: '/debts'
      fullPath: '/debts/'
      preLoaderRoute: typeof ProtectedDebtsIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/debts/new': {
      id: '/_protected/debts/new'
      path: '/debts/new'
      fullPath: '/debts/new'
      preLoaderRoute: typeof ProtectedDebtsNewRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedPaymentHistoryRoute: typeof ProtectedPaymentHistoryRoute
  ProtectedPaymentScheduleRoute: typeof ProtectedPaymentScheduleRoute
  ProtectedDebtsNewRoute: typeof ProtectedDebtsNewRoute
  ProtectedDebtsIndexRoute: typeof ProtectedDebtsIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedPaymentHistoryRoute: ProtectedPaymentHistoryRoute,
  ProtectedPaymentScheduleRoute: ProtectedPaymentScheduleRoute,
  ProtectedDebtsNewRoute: ProtectedDebtsNewRoute,
  ProtectedDebtsIndexRoute: ProtectedDebtsIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface SiteRouteRouteChildren {
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteRouteChildren: SiteRouteRouteChildren = {
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteRouteWithChildren = SiteRouteRoute._addFileChildren(
  SiteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  SiteRouteRoute: SiteRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
